services:  

  nginx:
    image: nginx:1.27-bookworm
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      first:
        ipv4_address: 10.100.11.11

  php:
    build:
      ./php
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
     first:
       ipv4_address: 10.100.11.12
     second:
       ipv4_address: 10.100.12.12

  db:
    image: postgres:16.3-alpine3.20
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
     second:
       ipv4_address: 10.100.12.13

#DB managment
#  adminer:
#    image: adminer:4.8.1
#    links: 
#      - db:db
#    ports:
#      - 8082:80
#    environment:
#      POSTGRES_PASSWORD: password
#    depends_on:
#      - db
#    networks:
#     second:
#       ipv4_address: 10.100.12.14

networks:
  first:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.11.0/24
  second:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.12.0/24